# Allow lines to be as long as 120.
line-length = 120
target-version = "py313"

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = false

[lint]
select = [
    "A",
    "B",
    "C90",
    "E",
    "F",
    "W",
    "S",
    "RUF",
    "PL",
    "FA",
    "UP",
    "SIM",
    "D4",
    "N",
    "PERF",
    "NPY",
    "TID",
    "BLE",
    "PIE",
    "ICN",
    "ISC",
    "PYI",
    "ANN",
]
ignore = [
    "E712",
    "PLR2004",
    "S301",
    "S104",
    "BLE001",
    "N815",
    "RUF001"
]

[lint.per-file-ignores]
"test_*.py" = ["S101", "D", "ANN", "BLE001", "SIM117", "UP041", "S104", "S105"]

[lint.pycodestyle]
ignore-overlong-task-comments = true

[lint.mccabe]
max-complexity = 6
